#!/sbin/sh
#
# CDDL HEADER START
#
# The  contents of this file are subject to the terms of the Common
# Development and  Distribution  License,  Version  1.0  only  (the
# "License").  You  may not use this file except in compliance with
# the License.
#
# A  copy  of  the  Common  Development and Distribution License is
# available at:
#
# https://github.com/UX-admin/rpmmacros/blob/master/LICENSE
#
# see the License for the specific language  governing  permissions
# and limitations under the License.
#
# When  distributing Covered Code, include this CDDL header in each
# file, and include the "LICENSE" file.
#
# If applicable, add the following below this CDDL header, with the
# fields   enclosed   by  brackets  "[]"  replaced  with  your  own
# identifying  information:  Portions  Copyright  [yyyy]  [name  of
# copyright owner]
#
# CDDL HEADER END
#
PKG_INSTALL_ROOT="${PKG_INSTALL_ROOT:-/}"; export PKG_INSTALL_ROOT
BaseDir="${PKG_INSTALL_ROOT}/${RTP_BASE}"
ISA64=`ls -l "${PKG_INSTALL_ROOT}/usr/lib/64" | awk '{print $NF;}'`

if [ ! -h "${BaseDir}/lib/64" ]
then
	cd "${BaseDir}/lib/" && ln -s "${ISA64}" "64"
fi
chown -h ${RTP_LOGIN}:${RTP_GROUP} "${BaseDir}/lib/64"
installf "${PKGINST}" "/${RTP_BASE}/lib/64"
installf -f "${PKGINST}"

case "${PKG_INSTALL_ROOT}"
in
	""|/)
		svcs -H "${RTP_WINDEX_FMRI}:${RTP_WINDEX_INSTANCE}" > /dev/null 2>&1 && svcadm refresh "${RTP_WINDEX_FMRI}:${RTP_WINDEX_INSTANCE}" || true
	;;
esac
